### ISSUE TITLE
Prettify JSON

### ISSUE THREAD

**Issue by ameenross** [nathan-osman/REST-Easy#19]
Would be cool if JSON could be prettified. IMO it makes sense to do so in the "preview" tab.

This:
```json
{"parameter1":"value1","parameter2":"value2"}
```
should become this:
```json
{
    "parameter1": "value1",
    "parameter2": "value2"
}
```

**Comment by set-killer** [comment]
Since the pull request of @mikegioia  is outdated, i've tryed to implenet the json preview.
Everything looks fine but i have a hard time using the localization strings.
Here is everything i have made for now:
https://github.com/set-killer/REST-Easy/commit/ca3e2f7ed6aa99d4d1a59e9bc57a4913693b7d67

@nathan-osman could you please give me support on this localization strings? 
They are just 2 strings that can't call inside resteasy.html and application.js
response.jsonn.title
response.jsonn.error
If you have any other remarks on the code, please tell me to fix them. Then i can make pull request.

**Comment by nathan-osman** [comment]
To answer your first question, you can access localized strings using:

    tr(string_name)

For example:

    var username = tr('request.auth.username');

However, I'm not sure that adding a new tab is the best way to present the prettified JSON. The Raw tab is supposed to display the content exactly the way it was received over-the-wire. The Preview tab would probably be a more appropriate place to display the prettified JSON.

**Comment by set-killer** [comment]
Thank you for the comment. That way it was much easier to implement. I've tryed to keep the code consistent.
The pull request is here:
https://github.com/nathan-osman/REST-Easy/pull/33/files

If there are is anything that i have to change on the code, please tell me to fix it.

**Comment by nathan-osman** [comment]
Looks good, thanks!
